title: Xie Zhengyang(谢正扬)'s Homepage
page-top-title: Xie Zhengyang
top-section-bg-text: Automation
home-subtitle: Xie Zhengyang&ensp;|&ensp;谢正扬
copyright-text: '&copy; Xie Zhengyang 2025-2026. All Rights Reserved.'
